development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: CommeCi_production

  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>